name: CI Pipeline
on:
  push:
    branches: [master]
env:
  PROJECT_ID: searce-cloud-consultants
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Configure Authentication with GCP
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "{{ secrets.ACTIONS_SA_KEY }}"

      - name: Build and Push Image using Cloud Build
        uses: google-github-actions/setup-gcloud@v0
      
      - name: Configure GCP Project
        run: gcloud config set project "$PROJECT_ID" 

      - name: Build Docker Image using Cloud Build
        run : gcloud builds submit --tag asia-south1-docker.pkg.dev/"$PROJECT_ID"/first-repository/app-image:${{ github.sha }} .
          